# Prerequisite

Following packages must be installed to run codes below

```bash
$ pip3 install openpyxl 
```

In [3]:
%load_ext autoreload
%autoreload 2

# Add project path

In [2]:
import os
import sys
from pathlib import Path

PROJECT_PATH = Path().resolve().parent.parent
SRC_PATH = PROJECT_PATH / 'src'

sys.path.append(str(SRC_PATH))

# Load data

In [3]:
from project_paths import DATA_PATH
from data_loader import DataLoader
data_loader = DataLoader(data_path=DATA_PATH)

In [4]:
finance_data = data_loader.load_finance_data()
finance_data.columns

Index(['사업자번호', '결산년월', '유동자산', '매출채권', '비유동자산', '유형자산', '자산총계', '유동부채',
       '비유동부채', '부  채  총  계', '자본금', '이익잉여금(결손금）', '자본총계', '매출액', '판매비와관리비',
       '영업이익（손실）', '법인세비용차감전순손익', '법인세비용', '당기순이익(손실)', '기업순이익률(%)',
       '유보액/총자산(%)', '유보액/납입자본(%)', '매출액총이익률(%)', '매출액영업이익률(%)', '매출액순이익률(%)',
       '수지비율(%)', '경상수지비율', '영업비율(%)', '금융비용대매출액비율(%', '금융비용대부채비율(%)',
       '금융비용대총비용비율(%', '부채비율(%)', '차입금의존도(%)', '자기자본비율(%)', '순운전자본비율(%)',
       '유동부채비율(%)', '비유동부채비율(%)', '부채총계대 매출액(%)', '총자본회전율(회)', '재고자산회전율(회)',
       '매출채권회전율(회)', '매입채무회전율(회)', '미수금', '매출원가', '무형자산', '재고자산'],
      dtype='object')

In [5]:
finance_data

,사업자번호,결산년월,유동자산,매출채권,비유동자산,유형자산,자산총계,유동부채,비유동부채,부 채 총 계,...,비유동부채비율(%),부채총계대 매출액(%),총자본회전율(회),재고자산회전율(회),매출채권회전율(회),매입채무회전율(회),미수금,매출원가,무형자산,재고자산
0,1018100340,20181231,2667731.0,127320.0,32346444.0,1179096.0,35014174.0,422872.0,16176067.0,16598939.0,...,8.784100e+01,2.503810e+02,1.630000e-01,1.000000e+12,4.406200e+01,1.000000e+12,NaN,NaN,NaN,NaN
1,1018100340,20191231,2168837.0,94085.0,34151633.0,1209369.0,36320470.0,10553878.0,5240445.0,15794323.0,...,2.550000e+01,2.414000e+02,1.840000e-01,1.000000e+12,5.909200e+01,NaN,NaN,NaN,NaN,NaN
2,1018100340,20201231,2272260.0,78612.0,38329680.0,1091153.0,40601940.0,863144.0,15496117.0,16359261.0,...,6.392100e+01,2.757190e+02,1.540000e-01,1.000000e+12,6.871400e+01,1.000000e+12,NaN,NaN,NaN,NaN
3,1018100340,20211231,1175030.0,273522.0,37135811.0,993025.0,38310842.0,9494272.0,4901383.0,14395654.0,...,2.049500e+01,2.337490e+02,1.560000e-01,1.000000e+12,3.497900e+01,1.000000e+12,3243.0,NaN,NaN,NaN
4,1018100772,20181231,422146.0,17011.0,20370096.0,20352846.0,20792242.0,2684934.0,11404637.0,14089571.0,...,1.701510e+02,1.250082e+03,5.500000e-02,1.000000e+12,6.971100e+01,1.000000e+12,386880.0,524746.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109137,8998800427,20211231,9192992.0,2918329.0,9735232.0,9409374.0,18928223.0,11017981.0,6619380.0,17637362.0,...,5.127880e+02,7.009100e+01,1.477000e+00,6.785000e+00,7.950000e+00,9.792000e+00,331735.0,23370771.0,75451.0,3680509.0
109138,8998800785,20181231,3608435.0,NaN,271541001.0,271541001.0,275149436.0,164335821.0,76480438.0,240816259.0,...,1.000000e+12,1.000000e+12,1.000000e+12,1.000000e+12,1.000000e+12,1.000000e+12,NaN,NaN,NaN,NaN
109139,8998800785,20191231,475283.0,NaN,309796969.0,309796969.0,310272251.0,3722434.0,274776917.0,278499351.0,...,1.000000e+12,8.888889e+11,0.000000e+00,1.000000e+12,1.000000e+12,1.000000e+12,NaN,NaN,NaN,NaN
109140,8998800785,20201231,1474607.0,NaN,366181956.0,366181956.0,367656563.0,1593683.0,335844394.0,337438077.0,...,1.000000e+12,8.888889e+11,0.000000e+00,1.000000e+12,1.000000e+12,1.000000e+12,NaN,NaN,NaN,NaN
109141,8998800785,20211231,2540577.0,1201346.0,422469161.0,420110684.0,425009738.0,282361726.0,125659808.0,408021534.0,...,1.000000e+12,3.711585e+04,3.000000e-03,1.000000e+12,1.000000e+12,1.000000e+12,NaN,NaN,NaN,NaN

In [6]:
meta_data = data_loader.load_meta_data()
meta_data

,순서,테이블명,영문칼럼명,한글칼럼명,칼럼형식,디폴트값,NULL여부,비고
0,1.0,기업개요,BIZ_NO,사업자등록번호,VARCHAR2(10),'Z',N,NaN
1,2.0,기업개요,CMP_PFIX_NM,기업접두명,VARCHAR2(64),NaN,Y,NaN
2,3.0,기업개요,CMP_NM,기업명,VARCHAR2(128),NaN,Y,NaN
3,4.0,기업개요,CMP_SFIX_NM,기업접미명,VARCHAR2(64),NaN,Y,NaN
4,5.0,기업개요,CMP_ENM,기업영문명,VARCHAR2(256),NaN,Y,NaN
5,6.0,기업개요,BZ_TYP,업종,VARCHAR2(3),NaN,N,NaN
6,7.0,기업개요,CMP_SCL,기업규모,VARCHAR2(3),NaN,Y,NaN
7,8.0,기업개요,PBCO_GB,공기업구분 1.공기업 2.일반기업,VARCHAR2(3),NaN,N,NaN
8,9.0,기업개요,PSN_CORP_GB,개인법인구분 1.법인 2.개인,VARCHAR2(3),NaN,N,NaN
9,10.0,기업개요,HDOF_BR_GB,본점지점구분 1.본점 2.지점,VARCHAR2(3),NaN,N,NaN
10,11.0,기업개요,FR_IVST_CORP_YN,국외투자법인여부,VARCHAR2(1),NaN,N,NaN
11,12.0,기업개요,VENT_YN,벤처기업여부,VARCHAR2(1),NaN,N,NaN
12,13.0,기업개요,LIST_CD,상장코드,VARCHAR2(10),NaN,Y,NaN
13,14.0,기업개요,IND_CD_ORDR,산업코드차수,NUMBER(5),NaN,Y,NaN
14,15.0,기업개요,IND_CD1,산업코드1,VARCHAR2(6),NaN,Y,NaN
15,16.0,기업개요,IND_CD2,산업코드2,VARCHAR2(6),NaN,Y,NaN
16,17.0,기업개요,IND_CD3,산업코드3,VARCHAR2(6),NaN,Y,NaN
17,18.0,기업개요,PB_ORG_TYP,공공기관유형,VARCHAR2(3),'0',N,NaN
18,19.0,기업개요,MDSCO_PRTC_YN,중견기업보호여부,VARCHAR2(1),'N',N,NaN
19,20.0,기업개요,HDOF_CMP_CD,본점기업코드,NUMBER(10),NaN,Y,NaN
20,21.0,기업개요,ESTB_DATE,설립일자,VARCHAR2(8),NaN,Y,NaN
21,22.0,기업개요,ESTB_GB,설립구분,VARCHAR2(3),NaN,Y,NaN
22,23.0,기업개요,LIST_DATE,상장일자,VARCHAR2(8),NaN,Y,NaN
23,24.0,기업개요,MN_BIZ_CONT,주요사업내용,VARCHAR2(256),NaN,Y,NaN
24,25.0,기업개요,NATN_NM,국가명,VARCHAR2(64),NaN,Y,NaN
25,26.0,기업개요,HOMEPAGE_URL,홈페이지URL,VARCHAR2(128),NaN,Y,NaN
26,27.0,기업개요,CEO_NM,대표자명,VARCHAR2(128),NaN,Y,NaN
27,28.0,기업개요,EMP_CNT,직원수,NUMBER(10),NaN,Y,NaN
28,29.0,휴폐업정보,BIZ_NO,사업자등록번호,VARCHAR2(10),'Z',N,NaN
29,30.0,휴폐업정보,END_DATE,종료일자,VARCHAR2(8),NaN,N,가장 최신 데이터는 99991231의 값을 가짐
30,31.0,휴폐업정보,STRT_DATE,시작일자,VARCHAR2(8),NaN,N,NaN
31,32.0,휴폐업정보,CLSBZ_GB,휴폐업구분,VARCHAR2(3),NaN,Y,NaN
32,33.0,휴폐업정보,STAT_OCR_DATE,상태발생일자,VARCHAR2(8),NaN,Y,2018.01~2022.08 휴폐업 기업
33,34.0,기업재무,BIZ_NO,사업자등록번호,VARCHAR2(10),'Z',N,NaN
34,35.0,기업재무,STT_YR,결산년도,VARCHAR2(8),NaN,N,2019~2022 결산기준
35,36.0,기업재무,ACCT_CD,계정코드,VARCHAR2(6),NaN,N,NaN
36,37.0,기업재무,ACCT_NM,계정명,VARCHAR2(256),NaN,N,NaN
37,38.0,기업재무,ACCT_AMT,계정금액,NUMBER(15),NaN,Y,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,,NaN,NaN,NaN,NaN

In [7]:
description_data_code = data_loader.load_description_data(sheet_name='코드집')
description_data_code

,GRP_CD,CD,END_DATE,STRT_DATE,CD_NM
0,BZ_TYP,A,99991231,20191201,신금(신용금고) -> 중소기업과 국민대중을 위한 자금을 융통하며 저축의 증대를 목적...
1,BZ_TYP,B,99991231,20191201,은행
2,BZ_TYP,C,99991231,20191201,카드
3,BZ_TYP,F,99991231,20191201,생보(생명보험) -> 보험사고 발생 객체가 피보험자의 생명 혹은 신체
4,BZ_TYP,I,99991231,20191201,손보(손해보험) -> 보험사고 발생 객체가 피보험자의 재산
5,BZ_TYP,M,99991231,20191201,제조
6,BZ_TYP,O,99991231,20191201,기타금융
7,BZ_TYP,S,99991231,20191201,증권
8,BZ_TYP,V,99991231,20191201,창투(창업투자회사) -> 창의성과 사업성은 있으나 자금력이 부족한 창업자에게 투자 ...
9,CMP_SCL,1,99991231,20191201,대기업
10,CMP_SCL,2,99991231,20191201,중소기업
11,CMP_SCL,3,99991231,20191201,기타(비영리법인)
12,CMP_SCL,4,99991231,20191201,중견기업
13,CMP_SCL,5,99991231,20191201,대기업(금융)
14,CMP_SCL,6,99991231,20191201,중견기업(하)
15,PBCO_GB,1,99991231,20191201,공기업
16,PBCO_GB,2,99991231,20191201,일반기업
17,PSN_CORP_GB,1,99991231,20191201,법인
18,PSN_CORP_GB,2,99991231,20191201,개인
19,HDOF_BR_GB,1,99991231,20191201,본점
20,HDOF_BR_GB,2,99991231,20191201,지점
21,PB_ORG_TYP,0,99991231,20191201,해당사항없음
22,PB_ORG_TYP,1,99991231,20191201,정부기구
23,PB_ORG_TYP,2,99991231,20191201,공기업/준정부기관
24,PB_ORG_TYP,3,99991231,20191201,지자체공단/공사
25,ESTB_GB,01,99991231,20191201,주식
26,ESTB_GB,02,99991231,20191201,합자
27,ESTB_GB,03,99991231,20191201,합명
28,ESTB_GB,04,99991231,20191201,유한
29,ESTB_GB,05,99991231,20191201,조합
30,ESTB_GB,06,99991231,20191201,정부투자기관
31,ESTB_GB,07,99991231,20191201,개인
32,ESTB_GB,08,99991231,20191201,학교
33,ESTB_GB,09,99991231,20191201,병원
34,ESTB_GB,10,99991231,20191201,단체.협회
35,ESTB_GB,11,99991231,20191201,<미정의>
36,ESTB_GB,99,99991231,20191201,기타
37,CLSBZ_GB,1,99991231,20191201,부도
38,CLSBZ_GB,2,99991231,20191201,휴업
39,CLSBZ_GB,3,99991231,20191201,폐업
40,CLSBZ_GB,4,99991231,20191201,피합병
41,CLSBZ_GB,5,99991231,20191201,휴업취소
42,CLSBZ_GB,6,99991231,20191201,폐업취소

In [8]:
description_data_financial_code = data_loader.load_description_data(sheet_name='재무계정')
description_data_financial_code

        계정코드    순번         계정명                           영문
0     M11000     1        유동자산               Current Assets
1     M11001     2      *국고보조금          *Governments Grants
2     M11002     3          현금                         Cash
3     M11003     4          외화           Foreign Currencies
4     M11004     5          예금                Bank Deposits
...      ...   ...         ...                          ...
2050  MG1400  2051     변동비율(%)      Variable Costs Ratio(%)
2051  MG1500  2052    공헌이익률(%)  Contribution Margin Rate(%)
2052  MG1600  2053   손익분기점률(%)    Break-Even Point Ratio(%)
2053  MG1700  2054  안전한계(안전이익)             Margin of Safety
2054  MG1800  2055       안전이익률      Marginal Rate of Safety

[2055 rows x 4 columns]

In [2]:
import pandas as pd

company_data_active = (
    data_loader.load_company_data(closed=False)
    .assign(Closed=False)
)
company_data_closed = (
    data_loader.load_company_data(closed=True)
    .assign(Closed=True)
)
company_data = pd.concat([company_data_active, company_data_closed], axis=0)

column_intersection = list(set(meta_data['영문칼럼명'].tolist()).intersection(set(company_data.columns.tolist())))
column_mapping = meta_data.loc[lambda x : x['영문칼럼명'].isin(column_intersection), ['영문칼럼명', '한글칼럼명']].set_index('영문칼럼명').to_dict()['한글칼럼명']

company_data = (
    company_data.rename(columns=column_mapping)
)

NameError: name 'data_loader' is not defined

In [1]:
company_data

NameError: name 'company_data' is not defined

In [10]:
company_data.T

,0,1,2,3,4,5,6,7,8,9,...,6822,6823,6824,6825,6826,6827,6828,6829,6830,6831
사업자등록번호,2218116923,1138111739,1108146490,3128134737,2078132193,4028122626,2228111902,3098101550,1318141997,4088112223,...,1668602001,1338801710,5678101364,3908500711,3898602225,4808501629,8018501578,4118523419,1738102533,3138135248
기업접두명,NaN,NaN,(주),(주),(주),(주),NaN,(주),NaN,(주),...,(주),(주),NaN,NaN,(주),NaN,(주),(주),(주),NaN
기업명,NaN,한일가스산업(주),NaN,NaN,(주)엠피아이,NaN,NaN,NaN,NaN,NaN,...,오너럽,대영케이티펙,피앤이씨,남순남주식회사증평제일공장\t,양심모터스,게방식당팩토리,우진푸드중부지점,윤월드푸드코리아다크써클브로스,기린테크,우리로봇
CMP_NM1,신우종합건설,한일가스산업,랩솔루션,고려인삼제품공사,엠피아이,디자인밸리,대신산업,서천신문,삼보하이테크,동양건설,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
기업접미명,(주),(주),NaN,NaN,NaN,NaN,(주),NaN,(주),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(주)
기업영문명,"Shinu General Construction Co., Ltd.","HANIL GAS IND. CO.,LTD.",Lab Solution,"KOREAN GINSENG PRODUCT CO., LTD","EMPIALEE CO.,LTD.",Design Valley,"Daesin Industrial Co, Ltd","NEWSN Co.,Ltd.","Sambo Hitech Co., Ltd.","Dongyang Construction Co.,Ltd.",...,"O Neoreob Co., Ltd.","Daeyoung KT Pek Co., Ltd.",P&EC Inc.,Namsunnam Stock Company Jeungpyeongje 1Factory,"Yangshim Motors Co., Ltd.",gebangsikdangfactory,woojinfood,"Youn World Food Korea Co., Ltd.","Girin Tech Co., Ltd.","Woori Robot Co., Ltd."
업종,M,M,M,M,M,M,M,M,M,M,...,M,M,M,M,M,M,M,M,M,M
CMP_TYP,4.0,3.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
기업규모,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
공기업구분 1.공기업 2.일반기업,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
개인법인구분 1.법인 2.개인,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
본점지점구분 1.본점 2.지점,1,1,1,1,1,1,1,1,1,1,...,1,1,1,2,1,2,2,2,1,1
국외투자법인여부,N,N,N,N,N,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,N
벤처기업여부,N,N,N,N,N,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,Y
상장코드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
산업코드차수,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,NaN,10.0,10.0,10.0,10.0,10.0,10.0,10.0
산업코드1,41200.0,47712.0,27210.0,10795.0,15190.0,33999.0,23322.0,58122.0,26421.0,42321.0,...,20423.0,46521.0,28422.0,10129.0,45120.0,10200.0,10122.0,56111.0,58222.0,29280.0
산업코드2,NaN,NaN,27213.0,NaN,NaN,73209.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56121.0,NaN,NaN
산업코드3,NaN,NaN,NaN,NaN,NaN,42400.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
공공기관유형,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
중견기업보호여부,N,N,N,N,N,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,N
TAXN_TYP,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
본점기업코드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5988109.0,NaN,8474403.0,4033821.0,9189675.0,NaN,NaN
설립일자,20000807.0,19660419.0,20000612.0,19920301.0,19910806.0,19970117.0,20001216.0,19891119.0,19910802.0,19890921.0,...,20201218.0,20210107.0,20191108.0,20141201.0,20210415.0,20180126.0,20200727.0,20190926.0,20211025.0,20200629.0
설립구분,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
상장일자,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
주요사업내용,토목공사업,LP Gas 충전 및 판매업,기체분석기 등,"다류, 차, 인삼제품, 음료, 코코아가공품, 커피",가죽 및 대용가죽제품 제조업,"버스승강장, 컨테이너하우스, 이동식초소 등",레미콘,지역신문사,유선통신장비 제조업,일반 통신 공사업,...,"1. 화장품 제조, 도소매, 수출입업","1. 마스크기계 제작, 수입 및 판매업",LED 조명기기,가정간편식 순대국 외,중고자동차 매매 및 알선,간장게장(장류),"돈가스, 탕수육, 꿔바로우","한식, 중식",1.인공지능(AI) 솔루션 구축 및 관련사업,NaN
국가명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
홈페이지URL,NaN,www.hanilgas.com,www.lab-solution.com,www.kitea.co.kr,www.mastercnd.co.kr,www.designv.kr,NaN,NaN,www.sbcctv.co.kr,NaN,...,www.ownerup.co.kr/,NaN,www.pnec.co.kr,www.nsnfood.com,NaN,https://gebangsikdang.modoo.at/,우진푸드.com,NaN,NaN,NaN
대표자명,김주대외 1명,홍순철외 1명,김봉철,박경출,이스테판상수외 1명,정예지,김범수,강신설,배성한,이민수,...,신광석,김규수,김서라,정승환,김남수,방건혁,신남정,윤인수,임계현,오석환
직원수,12.0,43.0,3.0,24.0,35.0,7.0,10.0,4.0,28.0,12.0,...,NaN,NaN,4.0,NaN,NaN,NaN,22.0,0.0,NaN,NaN
종료일자,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99991231.0,99991231.0,99991231.0,99991231.0,99991231.0,99991231.0,99991231.0,99991231.0,99991231.0,99991231.0
시작일자,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20220330.0,20220729.0,20220630.0,20220727.0,20220630.0,20211231.0,20211126.0,20220630.0,20220731.0,20220511.0
휴폐업구분,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
상태발생일자,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20220330.0,20220729.0,20220630.0,20220727.0,20220630.0,20211231.0,20211126.0,20220630.0,20220731.0,20220511.0
Closed,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [16]:
data_loader.load_ksic_data()

,대분류_코드,대분류,중분류_코드,중분류,소분류_코드,소분류,세분류_코드,세분류,세세분류_코드,세세분류
2,A,"농업, 임업 및 어업(01~03)",01,농업,011,작물 재배업,0111,곡물 및 기타 식량작물 재배업,01110,곡물 및 기타 식량작물 재배업
3,A,"농업, 임업 및 어업(01~03)",01,농업,011,작물 재배업,0112,"채소, 화훼작물 및 종묘 재배업",01121,채소작물 재배업
4,A,"농업, 임업 및 어업(01~03)",01,농업,011,작물 재배업,0112,"채소, 화훼작물 및 종묘 재배업",01122,화훼작물 재배업
5,A,"농업, 임업 및 어업(01~03)",01,농업,011,작물 재배업,0112,"채소, 화훼작물 및 종묘 재배업",01123,종자 및 묘목 생산업
6,A,"농업, 임업 및 어업(01~03)",01,농업,011,작물 재배업,0113,"과실, 음료용 및 향신용 작물 재배업",01131,과실작물 재배업
...,...,...,...,...,...,...,...,...,...,...
1194,T,가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동(97~98),97,가구 내 고용활동,970,가구 내 고용활동,9700,가구 내 고용활동,97000,가구 내 고용활동
1195,T,가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동(97~98),98,달리 분류되지 않은 자가 소비를 위한 가구의 재화 및 서비스 생산활동,981,자가 소비를 위한 가사 생산 활동,9810,자가 소비를 위한 가사 생산 활동,98100,자가 소비를 위한 가사 생산 활동
1196,T,가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동(97~98),98,달리 분류되지 않은 자가 소비를 위한 가구의 재화 및 서비스 생산활동,982,자가 소비를 위한 가사 서비스 활동,9820,자가 소비를 위한 가사 서비스 활동,98200,자가 소비를 위한 가사 서비스 활동
1197,U,국제 및 외국기관(99),99,국제 및 외국기관,990,국제 및 외국기관,9900,국제 및 외국기관,99001,주한 외국 공관
1198,U,국제 및 외국기관(99),99,국제 및 외국기관,990,국제 및 외국기관,9900,국제 및 외국기관,99009,기타 국제 및 외국기관