# Prerequisite

Following packages must be installed to run codes below

```bash
$ pip3 install openpyxl
```

# References

In [1]:
%load_ext autoreload
%autoreload 2

# Add project path

In [3]:
import os
import sys
from pathlib import Path

PROJECT_PATH = Path().resolve().parent.parent
SRC_PATH = PROJECT_PATH / 'src'

sys.path.append(str(SRC_PATH))

In [4]:
SRC_PATH

PosixPath('/home/nicednb/src')

# Load data

In [5]:
from data_loader import IndexDataLoader

index_data_loader = IndexDataLoader()

In [6]:
index_data_loader.load_csi()

   YEAR_MONTH  CSI
0  2018-01-01  111
1  2018-02-01  109
2  2018-03-01  109
3  2018-04-01  108
4  2018-05-01  109
5  2018-06-01  106
6  2018-07-01  102
7  2018-08-01  100
8  2018-09-01  101
9  2018-10-01  100
10 2018-11-01   96
11 2018-12-01   98
12 2019-01-01   98
13 2019-02-01  100
14 2019-03-01  100
15 2019-04-01  102
16 2019-05-01   99
17 2019-06-01   98
18 2019-07-01   97
19 2019-08-01   94
20 2019-09-01   98
21 2019-10-01  100
22 2019-11-01  102
23 2019-12-01  101
24 2020-01-01  105
25 2020-02-01   98
26 2020-03-01   80
27 2020-04-01   73
28 2020-05-01   80
29 2020-06-01   84
30 2020-07-01   86
31 2020-08-01   90
32 2020-09-01   81
33 2020-10-01   93
34 2020-11-01   99
35 2020-12-01   91
36 2021-01-01   95
37 2021-02-01   97
38 2021-03-01  100
39 2021-04-01  102
40 2021-05-01  105
41 2021-06-01  110
42 2021-07-01  103
43 2021-08-01  102
44 2021-09-01  104
45 2021-10-01  107
46 2021-11-01  108
47 2021-12-01  104

In [5]:
index_data_loader.load_composite_index()

   YEAR_MONTH    CCI    CLI
0  2018-01-01  101.7  100.8
1  2018-02-01  101.9  100.8
2  2018-03-01  101.9  100.8
3  2018-04-01  101.8  100.4
4  2018-05-01  101.7  100.4
5  2018-06-01  101.8  100.3
6  2018-07-01  101.6  100.2
7  2018-08-01  101.5   99.8
8  2018-09-01  101.1   99.7
9  2018-10-01  100.9   99.4
10 2018-11-01  100.7   99.2
11 2018-12-01  100.5   98.9
12 2019-01-01  100.7   98.8
13 2019-02-01  100.1   98.6
14 2019-03-01  100.1   98.8
15 2019-04-01   99.8   98.7
16 2019-05-01  100.2   98.5
17 2019-06-01  100.2   98.2
18 2019-07-01  100.2   98.0
19 2019-08-01  100.4   97.9
20 2019-09-01  100.4   98.0
21 2019-10-01  100.3   98.4
22 2019-11-01  100.2   98.7
23 2019-12-01  100.5   99.1
24 2020-01-01  100.7   99.1
25 2020-02-01  100.0   99.0
26 2020-03-01   98.8   98.6
27 2020-04-01   97.6   98.3
28 2020-05-01   96.8   98.0
29 2020-06-01   97.0   98.3
30 2020-07-01   97.2   98.6
31 2020-08-01   97.7   99.0
32 2020-09-01   98.1   99.3
33 2020-10-01   98.6   99.7
34 2020-11-01   99.0  100.1
35 2020-12-01   99.0  100.4
36 2021-01-01   98.8  100.6
37 2021-02-01   98.8  100.8
38 2021-03-01   99.2  101.0
39 2021-04-01   99.9  101.4
40 2021-05-01  100.0  101.7
41 2021-06-01  100.0  101.9
42 2021-07-01  100.1  101.8
43 2021-08-01  100.2  101.6
44 2021-09-01  100.1  101.2
45 2021-10-01  100.2  100.9
46 2021-11-01  100.3  100.5
47 2021-12-01  101.0  100.4

In [6]:
index_data_loader.load_exchange_rate()

      PRICE CHANGE RATE YEAR_MONTH
59  1150.65      -4.61% 2017-01-01
58  1136.39      -1.24% 2017-02-01
57  1116.65      -1.74% 2017-03-01
56  1136.87       1.81% 2017-04-01
55  1118.65      -1.60% 2017-05-01
54  1144.43       2.30% 2017-06-01
53  1118.40      -2.27% 2017-07-01
52  1123.85       0.49% 2017-08-01
51  1144.29       1.82% 2017-09-01
50  1117.42      -2.35% 2017-10-01
49  1087.13      -2.71% 2017-11-01
48  1066.37      -1.91% 2017-12-01
47  1069.08       0.25% 2018-01-01
46  1084.21       1.42% 2018-02-01
45  1060.25      -2.21% 2018-03-01
44  1069.33       0.86% 2018-04-01
43  1079.59       0.96% 2018-05-01
42  1113.91       3.18% 2018-06-01
41  1112.25      -0.15% 2018-07-01
40  1115.46       0.29% 2018-08-01
39  1109.98      -0.49% 2018-09-01
38  1141.02       2.80% 2018-10-01
37  1119.44      -1.89% 2018-11-01
36  1113.30      -0.55% 2018-12-01
35  1111.40      -0.17% 2019-01-01
34  1124.60       1.19% 2019-02-01
33  1136.10       1.02% 2019-03-01
32  1163.25       2.39% 2019-04-01
31  1187.80       2.11% 2019-05-01
30  1155.38      -2.73% 2019-06-01
29  1187.32       2.76% 2019-07-01
28  1209.50       1.87% 2019-08-01
27  1198.09      -0.94% 2019-09-01
26  1169.24      -2.41% 2019-10-01
25  1180.70       0.98% 2019-11-01
24  1154.07      -2.26% 2019-12-01
23  1194.97       3.54% 2020-01-01
22  1200.20       0.44% 2020-02-01
21  1218.30       1.51% 2020-03-01
20  1212.94      -0.44% 2020-04-01
19  1231.49       1.53% 2020-05-01
18  1199.28      -2.62% 2020-06-01
17  1193.59      -0.47% 2020-07-01
16  1187.94      -0.47% 2020-08-01
15  1164.65      -1.96% 2020-09-01
14  1136.49      -2.42% 2020-10-01
13  1109.32      -2.39% 2020-11-01
12  1084.47      -2.24% 2020-12-01
11  1117.64       3.06% 2021-01-01
10  1123.89       0.56% 2021-02-01
9   1127.17       0.29% 2021-03-01
8   1117.16      -0.89% 2021-04-01
7   1106.58      -0.95% 2021-05-01
6   1130.48       2.16% 2021-06-01
5   1151.41       1.85% 2021-07-01
4   1158.73       0.64% 2021-08-01
3   1184.23       2.20% 2021-09-01
2   1174.47      -0.82% 2021-10-01
1   1182.71       0.70% 2021-11-01
0   1187.96       0.44% 2021-12-01

In [7]:
index_data_loader.load_interest_rate()

,3YEAR TREASURY,5YEAR TREASURY,10YEAR TREASURY,3YEAR COPORATE BOND,CD 91DAYS,CALL RATE 1DAY,BASE RATE,YEAR_MONTH
0,1.64,1.82,2.11,2.10,1.50,1.24,1.25,2017-01-01
1,1.67,1.86,2.16,2.13,1.49,1.23,1.25,2017-02-01
2,1.71,1.91,2.22,2.21,1.48,1.23,1.25,2017-03-01
3,1.68,1.86,2.18,2.20,1.43,1.23,1.25,2017-04-01
4,1.70,1.91,2.26,2.22,1.40,1.23,1.25,2017-05-01
5,1.67,1.86,2.17,2.21,1.38,1.24,1.25,2017-06-01
6,1.74,1.94,2.25,2.28,1.39,1.24,1.25,2017-07-01
7,1.78,1.99,2.29,2.32,1.39,1.23,1.25,2017-08-01
8,1.79,1.99,2.29,2.33,1.38,1.25,1.25,2017-09-01
9,2.03,2.25,2.46,2.57,1.38,1.24,1.25,2017-10-01
10,2.15,2.36,2.54,2.71,1.45,1.26,1.50,2017-11-01
11,2.10,2.30,2.47,2.65,1.66,1.51,1.50,2017-12-01
12,2.19,2.44,2.63,2.72,1.66,1.49,1.50,2018-01-01
13,2.28,2.54,2.77,2.82,1.65,1.49,1.50,2018-02-01
14,2.27,2.50,2.71,2.83,1.65,1.49,1.50,2018-03-01
15,2.19,2.44,2.66,2.79,1.65,1.47,1.50,2018-04-01
16,2.25,2.53,2.76,2.86,1.65,1.50,1.50,2018-05-01
17,2.18,2.44,2.66,2.81,1.65,1.49,1.50,2018-06-01
18,2.10,2.34,2.55,2.75,1.65,1.49,1.50,2018-07-01
19,2.02,2.24,2.46,2.66,1.65,1.50,1.50,2018-08-01
20,1.95,2.13,2.32,2.40,1.65,1.54,1.50,2018-09-01
21,2.01,2.16,2.34,2.45,1.68,1.52,1.50,2018-10-01
22,1.94,2.05,2.21,2.40,1.71,1.51,1.75,2018-11-01
23,1.83,1.89,1.99,2.30,1.91,1.77,1.75,2018-12-01
24,1.81,1.88,1.99,2.26,1.87,1.75,1.75,2019-01-01
25,1.80,1.87,1.99,2.25,1.87,1.76,1.75,2019-02-01
26,1.79,1.84,1.95,2.24,1.90,1.76,1.75,2019-03-01
27,1.74,1.77,1.89,2.21,1.89,1.75,1.75,2019-04-01
28,1.68,1.72,1.83,2.15,1.84,1.75,1.75,2019-05-01
29,1.50,1.53,1.62,2.00,1.80,1.76,1.75,2019-06-01
30,1.38,1.42,1.51,1.89,1.68,1.63,1.50,2019-07-01
31,1.16,1.20,1.25,1.69,1.49,1.51,1.50,2019-08-01
32,1.29,1.35,1.42,1.79,1.54,1.52,1.50,2019-09-01
33,1.36,1.44,1.58,1.86,1.46,1.35,1.25,2019-10-01
34,1.49,1.59,1.75,2.00,1.52,1.28,1.25,2019-11-01
35,1.39,1.48,1.65,1.95,1.53,1.28,1.25,2019-12-01
36,1.37,1.48,1.66,1.96,1.47,1.27,1.25,2020-01-01
37,1.25,1.36,1.54,1.85,1.42,1.24,1.25,2020-02-01
38,1.09,1.27,1.49,1.84,1.23,0.98,0.75,2020-03-01
39,1.02,1.26,1.50,2.15,1.10,0.74,0.75,2020-04-01
40,0.88,1.13,1.39,2.18,1.02,0.70,0.50,2020-05-01
41,0.85,1.13,1.39,2.22,0.79,0.48,0.50,2020-06-01
42,0.83,1.09,1.36,2.22,0.79,0.48,0.50,2020-07-01
43,0.83,1.09,1.37,2.19,0.68,0.50,0.50,2020-08-01
44,0.91,1.19,1.50,2.24,0.63,0.48,0.50,2020-09-01
45,0.91,1.20,1.51,2.24,0.63,0.51,0.50,2020-10-01
46,0.97,1.30,1.61,2.25,0.66,0.49,0.50,2020-11-01
47,0.97,1.32,1.68,2.21,0.66,0.51,0.50,2020-12-01
48,0.98,1.32,1.73,2.14,0.68,0.49,0.50,2021-01-01
49,1.00,1.35,1.85,2.06,0.73,0.49,0.50,2021-02-01
50,1.13,1.55,2.04,2.09,0.75,0.49,0.50,2021-03-01
51,1.14,1.58,2.04,1.98,0.74,0.48,0.50,2021-04-01
52,1.13,1.65,2.13,1.89,0.68,0.48,0.50,2021-05-01
53,1.30,1.70,2.10,1.91,0.66,0.51,0.50,2021-06-01
54,1.42,1.69,1.98,1.89,0.69,0.53,0.50,2021-07-01
55,1.41,1.65,1.91,1.84,0.77,0.56,0.75,2021-08-01
56,1.52,1.79,2.06,1.95,0.98,0.77,0.75,2021-09-01
57,1.84,2.15,2.40,2.30,1.08,0.74,0.75,2021-10-01
58,1.95,2.17,2.36,2.49,1.17,0.80,1.00,2021-11-01
59,1.80,1.98,2.19,2.41,1.27,1.01,1.00,2021-12-01

In [8]:
index_data_loader.load_consumer_price_index()

    KOR CPI YEAR_MONTH
0     97.37 2017-01-01
1     97.63 2017-02-01
2     97.57 2017-03-01
3     97.44 2017-04-01
4     97.55 2017-05-01
5     97.34 2017-06-01
6     97.50 2017-07-01
7     98.06 2017-08-01
8     98.17 2017-09-01
9     98.08 2017-10-01
10    97.35 2017-11-01
11    97.70 2017-12-01
12    98.11 2018-01-01
13    98.86 2018-02-01
14    98.75 2018-03-01
15    98.93 2018-04-01
16    98.98 2018-05-01
17    98.78 2018-06-01
18    98.59 2018-07-01
19    99.46 2018-08-01
20   100.22 2018-09-01
21   100.04 2018-10-01
22    99.33 2018-11-01
23    98.99 2018-12-01
24    98.88 2019-01-01
25    99.31 2019-02-01
26    99.12 2019-03-01
27    99.48 2019-04-01
28    99.65 2019-05-01
29    99.49 2019-06-01
30    99.19 2019-07-01
31    99.43 2019-08-01
32    99.79 2019-09-01
33   100.04 2019-10-01
34    99.48 2019-11-01
35    99.72 2019-12-01
36   100.09 2020-01-01
37   100.16 2020-02-01
38    99.94 2020-03-01
39    99.50 2020-04-01
40    99.44 2020-05-01
41    99.71 2020-06-01
42    99.63 2020-07-01
43   100.19 2020-08-01
44   100.74 2020-09-01
45   100.18 2020-10-01
46   100.09 2020-11-01
47   100.33 2020-12-01
48   101.04 2021-01-01
49   101.58 2021-02-01
50   101.84 2021-03-01
51   101.98 2021-04-01
52   102.05 2021-05-01
53   102.05 2021-06-01
54   102.26 2021-07-01
55   102.75 2021-08-01
56   103.17 2021-09-01
57   103.35 2021-10-01
58   103.87 2021-11-01
59   104.04 2021-12-01

In [9]:
index_data_loader.load_dow_jones_commodity_index()

     PRICE CHANGE RATE YEAR_MONTH
59  573.21       1.05% 2017-01-01
58  579.89       1.17% 2017-02-01
57  565.65      -2.46% 2017-03-01
56  560.96      -0.83% 2017-04-01
55  552.44      -1.52% 2017-05-01
54  554.89       0.44% 2017-06-01
53  574.40       3.52% 2017-07-01
52  580.62       1.08% 2017-08-01
51  585.74       0.88% 2017-09-01
50  600.73       2.56% 2017-10-01
49  606.92       1.03% 2017-11-01
48  625.37       3.04% 2017-12-01
47  639.53       2.26% 2018-01-01
46  630.91      -1.35% 2018-02-01
45  631.07       0.03% 2018-03-01
44  651.75       3.28% 2018-04-01
43  659.06       1.12% 2018-05-01
42  640.94      -2.75% 2018-06-01
41  622.12      -2.94% 2018-07-01
40  612.70      -1.52% 2018-08-01
39  625.37       2.07% 2018-09-01
38  613.02      -1.97% 2018-10-01
37  611.95      -0.18% 2018-11-01
36  572.87      -6.39% 2018-12-01
35  604.20       5.47% 2019-01-01
34  619.94       2.60% 2019-02-01
33  620.98       0.17% 2019-03-01
32  622.34       0.22% 2019-04-01
31  598.26      -3.87% 2019-05-01
30  619.41       3.53% 2019-06-01
29  613.07      -1.02% 2019-07-01
28  596.31      -2.73% 2019-08-01
27  605.09       1.47% 2019-09-01
26  619.10       2.31% 2019-10-01
25  609.84      -1.50% 2019-11-01
24  642.31       5.32% 2019-12-01
23  591.36      -7.93% 2020-01-01
22  563.68      -4.68% 2020-02-01
21  467.93     -16.99% 2020-03-01
20  469.15       0.26% 2020-04-01
19  531.78      13.35% 2020-05-01
18  561.30       5.55% 2020-06-01
17  591.33       5.35% 2020-07-01
16  635.22       7.42% 2020-08-01
15  626.67      -1.35% 2020-09-01
14  629.89       0.51% 2020-10-01
13  690.42       9.61% 2020-11-01
12  731.59       5.96% 2020-12-01
11  758.13       3.63% 2021-01-01
10  815.23       7.53% 2021-02-01
9   800.48      -1.81% 2021-03-01
8   866.92       8.30% 2021-04-01
7   892.34       2.93% 2021-05-01
6   896.01       0.41% 2021-06-01
5   906.40       1.16% 2021-07-01
4   894.41      -1.32% 2021-08-01
3   919.73       2.83% 2021-09-01
2   958.07       4.17% 2021-10-01
1   893.86      -6.70% 2021-11-01
0   946.24       5.86% 2021-12-01

In [10]:
index_data_loader.load_apartment_housing_index()

     NATIONWIDE  CAPITAL AREA  NON CAPITAL AREA YEAR_MONTH
0          60.0          62.8              57.6 2006-01-01
1          60.5          63.7              57.5 2006-02-01
2          61.2          64.8              57.6 2006-03-01
3          61.6          65.6              57.6 2006-04-01
4          62.0          66.2              57.6 2006-05-01
..          ...           ...               ...        ...
195       142.2         167.9             120.5 2022-04-01
196       141.0         166.1             119.9 2022-05-01
197       140.5         165.1             119.9 2022-06-01
198       137.1         159.2             118.5 2022-07-01
199       134.5         155.2             117.1 2022-08-01

[200 rows x 4 columns]

In [11]:
index_data_loader.load_import_export_performance()

    year country  trade balance
0   2017   china       44259886
1   2017     usa       17860364
2   2017   japan      -28308584
3   2018   china       55636464
4   2018     usa       13851619
5   2018   japan      -24075169
6   2019   china       28973797
7   2019     usa       11465334
8   2019   japan      -19160640
9   2020   china       23680800
10  2020     usa       16623642
11  2020   japan      -20925384
12  2021   china       24284847
13  2021     usa       22688542
14  2021   japan      -24580359